localclip script info should go to stderr

diff --git a/netclip b/netclip
--- a/netclip
+++ b/netclip
@@ -227,13 +227,13 @@ elif \$(is_windows) ; then
   test \"\${cincmd}\" == none && cincmd=clip.exe
   test \"\${coutcmd}\" == none && coutcmd=\"powershell.exe Get-Clipboard\"
 else
-  echo \"unhandled platform\"
+  echo \"unhandled platform\" 1>&2
 fi
 if [[ \${clipmode} == i ]] ; then
   if [[ \${cincmd} == none ]] ; then
-    echo \"cannot copy to local clipboard on this platform\"
+    echo \"cannot copy to local clipboard on this platform\" 1>&2
     if \$(is_linux || is_bsd) ; then
-      echo \"install xsel/xclip on linux/bsd or osc52.sh on chromeos\"
+      echo \"install xsel/xclip on linux/bsd or osc52.sh on chromeos\" 1>&2
     fi
     exit 1
   fi
@@ -245,9 +245,9 @@ if [[ \${clipmode} == i ]] ; then
   fi
 elif [[ \${clipmode} == o ]] ; then
   if [[ \${coutcmd} == none ]] ; then
-    echo \"cannot paste from local clipboard on this platform\"
+    echo \"cannot paste from local clipboard on this platform\" 1>&2
     if \$(is_linux || is_bsd) ; then
-      echo \"install xsel/xclip on linux/bsd\"
+      echo \"install xsel/xclip on linux/bsd\" 1>&2
     fi
     exit 1
   fi
